s3li:
  - vegetation
  - waterfront
  - straight_path
  - moon_lake
  - lava_tunnel
  - capo_grillo
  - capo_grillo_2
  - crater_inout
  - crater
  - landmarks
  - loops
  - mapping
  - traverse_1
  - traverse_2